version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: fix(deps)
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    commit-message:
      prefix: fix(deps)
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    commit-message:
      prefix: fix(deps)
    schedule:
      interval: daily
