version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    commit-message:
      prefix: "fix(deps)"
    schedule:
      interval: daily
    reviewers: [justenstall]
  - package-ecosystem: gomod
    directory: "/"
    commit-message:
      prefix: "fix(deps)"
    schedule:
      interval: daily
    reviewers: [justenstall]
  - package-ecosystem: docker
    directory: "/"
    commit-message:
      prefix: "fix(deps)"
    schedule:
      interval: daily
    reviewers: [justenstall]
