version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: daily
    reviewers: [justenstall]
  - package-ecosystem: gomod
    directory: "/"
    commit-message:
      prefix: "deps(gomod)"
    schedule:
      interval: daily
    reviewers: [justenstall]
  - package-ecosystem: docker
    directory: "/"
    commit-message:
      prefix: "deps(docker)"
    schedule:
      interval: daily
    reviewers: [justenstall]
