include:
  - project: devsecops/cicd/pipeline
    ref: v19.0.12
    file: main.yml

############################################################
# Build jobs
############################################################

build binaries:
  extends: .go build
  variables:
    CGO_ENABLED: 0
    EXECUTABLE: "hops"
  parallel:
    matrix:
      - GOOS:
          - linux
          - windows
          - darwin
        GOARCH:
          - amd64
          - arm64

build fips:
  extends: .go build fips
  variables:
    CGO_ENABLED: 0
    EXECUTABLE: "hops"

build image:
  variables:
    TARGET_STAGE: ""
  needs:
    - build binaries

############################################################
# Release jobs
############################################################

# Generates static Go package docs
generate go package docs:
  extends: .generate_go_package_docs
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: never
    - !reference [.standard_go_rules, rules]

# Deploys package docs and coverage report
pages:
  stage: Deploy
  needs:
    - generate go package docs
    - golang unit test
  rules: !reference ["generate go package docs", rules]
  image: cgr.dev/chainguard/wolfi-base
  script:
    - mkdir public
    - cp -r docs/pkg public/pkg
    - cp coverage.html public
    - echo "Pages accessible through ${CI_PAGES_URL}/${PAGES_PREFIX}"
  artifacts:
    paths:
      - public

# Release needs hops to run
# "hops gendocs" from release.sh
semantic release:
  dependencies:
    - build binaries
