linters:
  enable:
    - bodyclose
    - dupl
    - errname
    - errorlint
    - exhaustive
    - gochecknoinits
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - revive
    - sloglint
    - staticcheck
    - tenv
    - thelper
    - typecheck
    - unparam
    - unused
    - usestdlibvars

linters-settings:
  importas:
    # if set to `true`, force to use alias.
    no-unaliased: true
    # List of aliases
    alias:
      - pkg: github.com/opencontainers/image-spec/specs-go/v1
        alias: ocispec
      - pkg: github.com/act3-ai/hops/internal/apis/config.hops.io/v1beta1
        alias: hopsv1
      - pkg: github.com/act3-ai/hops/internal/apis/formulae.brew.sh/v1
        alias: brewv1
      - pkg: github.com/act3-ai/hops/internal/apis/formulae.brew.sh/v2
        alias: brewv2
      - pkg: github.com/act3-ai/hops/internal/apis/formulae.brew.sh/v3
        alias: brewv3

  sloglint:
    # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
    # Default: false
    attr-only: true
    # Enforce using static values for log messages.
    # Default: false
    # static-msg: true
    # Enforce a single key naming convention.
    # Values: snake, kebab, camel, pascal
    # Default: ""
    key-naming-case: camel

  staticcheck:
    # SAxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    # Default: ["*"]
    checks: ["all"]

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: unhandled-error
        arguments:
          - "fmt.Printf"
          - "fmt.Println"
          - "fmt.Print"
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: defer
      - name: useless-break
      - name: unexported-naming
      - name: cognitive-complexity
        arguments: [30]
      - name: use-any

  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    # Default: ""
    local-prefixes: gitlab.com/act3-ai,github.com/act3-ai

issues:
  # uncomment to enable more linting
  # exclude-use-default: false

  include:
    - EXC0005
    - EXC0012
    - EXC0009
    - EXC0002
