# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 1

builds:
  - id: default
    main: ./cmd/hops
    binary: bin/hops
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Tag}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds: [default]
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

dockers:
  # linux/amd64 image
  - id: hops-amd64
    goos: linux
    goarch: amd64
    ids: [default]
    image_templates:
      - "ghcr.io/act3-ai/hops:{{ .Tag }}_amd64"
      - "ghcr.io/act3-ai/hops:v{{ .Major }}_amd64"
      - "ghcr.io/act3-ai/hops:v{{ .Major }}.{{ .Minor }}_amd64"
      - "{{if not .Prerelease}}ghcr.io/act3-ai/hops:latest_amd64{{end}}"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=HOPS_EXECUTABLE=bin/hops"
      - "--label=org.opencontainers.image.created={{.CommitDate}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
  # linux/arm64 image
  - id: hops-arm64
    goos: linux
    goarch: arm64
    ids: [default]
    image_templates:
      - "ghcr.io/act3-ai/hops:{{ .Tag }}_arm64"
      - "ghcr.io/act3-ai/hops:v{{ .Major }}_arm64"
      - "ghcr.io/act3-ai/hops:v{{ .Major }}.{{ .Minor }}_arm64"
      - "{{if not .Prerelease}}ghcr.io/act3-ai/hops:latest_arm64{{end}}"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--build-arg=HOPS_EXECUTABLE=bin/hops"
      - "--label=org.opencontainers.image.created={{.CommitDate}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"

docker_manifests:
  - id: default
    skip_push: false
    name_template: ghcr.io/act3-ai/hops:{{ .Tag }}
    image_templates:
      - "ghcr.io/act3-ai/hops:{{ .Tag }}_amd64"
      - "ghcr.io/act3-ai/hops:{{ .Tag }}_arm64"
  - id: major
    skip_push: auto
    name_template: "ghcr.io/act3-ai/hops:v{{ .Major }}"
    image_templates:
      - "ghcr.io/act3-ai/hops:{{ .Tag }}_amd64"
      - "ghcr.io/act3-ai/hops:{{ .Tag }}_arm64"
  - id: majorminor
    skip_push: auto
    name_template: "ghcr.io/act3-ai/hops:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/act3-ai/hops:{{ .Tag }}_amd64"
      - "ghcr.io/act3-ai/hops:{{ .Tag }}_arm64"
  - id: latest
    skip_push: auto
    name_template: "ghcr.io/act3-ai/hops:latest"
    image_templates:
      - "ghcr.io/act3-ai/hops:{{ .Tag }}_amd64"
      - "ghcr.io/act3-ai/hops:{{ .Tag }}_arm64"

kos:
  - id: hops-slim
    build: default
    platforms:
      - all
    base_image: chainguard/static
    repository: ghcr.io/act3-ai/hops-slim
    base_import_paths: true
    tags:
      - "{{.Tag}}"
      - "{{if not .Prerelease}}v{{ .Major }}{{end}}"
      - "{{if not .Prerelease}}v{{ .Major }}.{{ .Minor }}{{end}}"
      - "{{if not .Prerelease}}latest{{end}}"
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"
    sbom: spdx
    labels:
      org.opencontainers.image.title: "hops"
      org.opencontainers.image.description: "Hops is a Homebrew Bottle installer with a focus on performance and mobility."
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Tag}}"
      org.opencontainers.image.licenses: "MIT"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.documentation: "{{.GitURL}}"
      org.opencontainers.image.url: "{{.GitURL}}"

report_sizes: true

release:
  prerelease: auto
  replace_existing_draft: true
  replace_existing_artifacts: true
  target_commitish: "{{ .Commit }}"
  make_latest: "{{ not .Prerelease }}"
  name_template: "Hops {{.Tag}}"
