# https://taskfile.dev

version: "3"

vars:
  ############################################################
  # Variables used by multiple tasks
  ############################################################
  REV:
    sh: git describe --long --tags --match='v*' --dirty 2>/dev/null || git rev-list -n1 HEAD
  IMAGE_REPO: ghcr.com/act3-ai/hops
  # Use port 5001 because the default podman machine uses port 5000
  TEST_REGISTRY_PORT: 5001
  TEST_REGISTRY_NAME: testreg

tasks:
  default:
    desc: "Build from source with -race flag"
    deps: [generate]
    env:
      CGO_ENABLED: 1
    cmds:
      - mkdir -p ./bin
      - go build -race -o bin/hops ./cmd/hops
    generates:
      - bin/hops

  build:
    desc: "Build from source"
    deps: [generate]
    env:
      CGO_ENABLED: 0
    cmds:
      - mkdir -p ./bin
      - go build -o bin/hops ./cmd/hops
    generates:
      - bin/hops

  build-trimmed:
    desc: "Build from source (stripped/trimmed)"
    deps: [generate]
    env:
      CGO_ENABLED: 0
    cmds:
      - mkdir -p ./bin
      - go build -trimpath -ldflags="-s -w" -o bin/hops ./cmd/hops
    generates:
      - bin/hops

  build-linux:
    desc: "Build from source for linux/amd64"
    aliases: [build-linux]
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    deps: [generate]
    cmds:
      - mkdir -p ./bin
      - go build -o bin/hops--linux-amd64 ./cmd/hops
    generates:
      - bin/hops--linux-amd64

  install:
    desc: "Install from source with go install"
    deps: [generate]
    cmds:
      - go install ./cmd/hops

  generate:
    desc: "Run go generate"
    cmds:
      - go generate ./...
    sources:
      - gen.go
      - internal/cli/
      - cmd/hops/
    generates:
      - docs/cli/

  lint:
    desc: "Lint project"
    deps:
      - golangci-lint
      - markdownlint
      - yamllint

  golangci-lint:
    desc: "Lint Go code with golangci-lint"
    preconditions:
      - sh: command -v golangci-lint
        msg: "golangci-lint is required. Install golangci-lint: https://golangci-lint.run/welcome/install/"
    cmds:
      - golangci-lint run

  markdownlint:
    desc: "Lint markdown with markdownlint-cli2"
    preconditions:
      - sh: command -v markdownlint-cli2
        msg: |
          markdownlint-cli2 is required.
          Install markdownlint-cli2:
            - Homebrew: brew install markdownlint-cli2
            - Docs: https://github.com/DavidAnson/markdownlint-cli2#install
    cmds:
      - markdownlint-cli2 .

  yamllint:
    desc: "Lint YAML with yamllint"
    preconditions:
      - sh: command -v yamllint
        msg: |
          yamllint is required.
          Install yamllint:
            - Homebrew: brew install yamllint
            - Docs: https://yamllint.readthedocs.io/en/stable/quickstart.html
    cmds:
      - yamllint .

  govulncheck:
    desc: "Check Go package vulnerabilities"
    vars:
      # renovate: datasource=go depName=golang.org/x/vuln/cmd/govulncheck
      GOVULNCHECK_VERSION: latest
    cmds:
      - >-
        go run
        golang.org/x/vuln/cmd/govulncheck@
        {{- .GOVULNCHECK_VERSION | default "latest" }}
        ./...

  test:
    desc: "Run unit tests"
    deps: [generate]
    aliases: [test-unit]
    cmds:
      - go test ./...

  runprof:
    desc: "Run CPU/memory profiling"
    deps: [generate]
    sources:
      - internal/**/*.go
    generates:
      - cpu.prof
      - mem.prof
    cmds:
      - "go test -cpuprofile cpu.prof -memprofile mem.prof -bench=. ./internal/actions -count=10"

  cpuprof:
    desc: "Run CPU/memory profiling"
    deps: [runprof]
    cmds:
      - "go tool pprof -http=: cpu.prof"

  memprof:
    desc: "Run CPU/memory profiling"
    deps: [runprof]
    cmds:
      - "go tool pprof -http=: mem.prof"

  clean:
    desc: Clean test directories
    cmds:
      - rm -rf HOPS_CACHE
      - rm -rf HOMEBREW_CACHE
      - rm -rf HOMEBREW_PREFIX
      - direnv reload

  image:
    desc: "Build container image with Docker"
    deps: [build-linux]
    cmds:
      - |
        docker build \
        --build-arg HOPS_EXECUTABLE=bin/hops--linux-amd64 \
        -t {{.IMAGE_REPO}} .

  image-run:
    desc: "Run latest docker container"
    cmds:
      - docker run -it {{.IMAGE_REPO}}:latest

  image-scan:
    desc: "Scan latest container image with grype"
    aliases: [grype]
    cmds:
      - grype {{.IMAGE_REPO}}:latest

  ko:
    desc: "Build multiplatform distroless image with ko"
    deps: [tool:ko]
    vars:
      # renovate: datasource=go depName=github.com/google/ko
      KO_VERSION: v0.17.1
    env:
      VERSION: "{{ .VERSION | default .REV }}"
      KO_DOCKER_REPO: '{{ .KO_DOCKER_REPO | default (printf "%s/distroless" .IMAGE_REPO) }}'
    cmds:
      - >-
        go run
        github.com/google/ko@
        {{- .KO_VERSION | default "latest" }}
        build -B --image-label version="{{.REV}}" ./cmd/hops

  startreg:
    desc: Start a local registry for testing purposes
    cmds:
      - podman run --name {{.TEST_REGISTRY_NAME}} --rm -d -p {{.TEST_REGISTRY_PORT}}:5000 registry:2
      - |
        echo "# To use the test registry, run the following:"
        echo "export HOPS_REGISTRY=localhost:{{.TEST_REGISTRY_PORT}}"
        echo "export HOPS_REGISTRY_PLAIN_HTTP=true"

  stopreg:
    desc: Start a local registry for testing purposes
    cmds:
      - podman stop {{.TEST_REGISTRY_NAME}}

  next-version:
    desc: Print next version
    cmds:
      - git cliff --bumped-version

  next-changelog:
    desc: Preview updated CHANGELOG.md
    vars:
      VERSION:
        sh: git cliff --bumped-version
    cmds:
      - git cliff --tag {{.VERSION}} --unreleased --strip header

  next-changelog-all:
    desc: Preview updated CHANGELOG.md
    vars:
      VERSION:
        sh: git cliff --bumped-version
    cmds:
      - git cliff --tag {{.VERSION}}

  git-status-clean:
    desc: Check Git status
    internal: true
    preconditions:
      - sh: '[ -z "$(git status --porcelain)" ]'
        msg: Git status unclean

  release-tag-internal:
    internal: true
    deps: [git-status-clean]
    requires:
      vars: [TAG]
    env:
      RELEASE_NOTES:
        sh: git cliff --tag "{{.TAG}}" --unreleased --strip header
    prompt: 'Create release tag "{{.TAG}}"?'
    cmds:
      - echo "{{.TAG}}" > VERSION
      - task: update-changelog
        vars:
          TAG: "{{.TAG}}"
      - git add VERSION CHANGELOG.md
      - 'git commit -m "chore(release): {{.TAG}}" -m "$RELEASE_NOTES"'
      - git tag "{{.TAG}}"

  release-tag:
    desc: Create release tag
    deps: [git-status-clean]
    cmds:
      - task: release-tag-internal
        vars:
          TAG:
            sh: git cliff --bumped-version

  release-tag-*:
    desc: Create specific release tag
    deps: [git-status-clean]
    cmds:
      - task: release-tag-internal
        vars:
          TAG: "{{index .MATCH 0}}"

  goreleaser:
    desc: Run GoReleaser
    deps: [git-status-clean]
    cmds:
      - |
        goreleaser release --clean \
          --release-notes <(git cliff --current --strip header | tail -n +3)

  update-changelog:
    desc: Update CHANGELOG.md
    requires:
      vars: [TAG]
    cmds:
      - git cliff --tag "{{.TAG}}" --output CHANGELOG.md
