// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1

import (
	json "encoding/json"
	common "github.com/act3-ai/hops/internal/apis/formulae.brew.sh/common"
	platform "github.com/act3-ai/hops/internal/platform"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV1(in *jlexer.Lexer, out *Versions) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Others":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Others = make(map[string]interface{})
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 interface{}
					if m, ok := v1.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v1.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v1 = in.Interface()
					}
					(out.Others)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "stable":
			out.Stable = string(in.String())
		case "head":
			if in.IsNull() {
				in.Skip()
				out.Head = nil
			} else {
				if out.Head == nil {
					out.Head = new(string)
				}
				*out.Head = string(in.String())
			}
		case "bottle":
			out.Bottle = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV1(out *jwriter.Writer, in Versions) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Others\":"
		out.RawString(prefix[1:])
		if in.Others == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Others {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				if m, ok := v2Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v2Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v2Value))
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"stable\":"
		out.RawString(prefix)
		out.String(string(in.Stable))
	}
	{
		const prefix string = ",\"head\":"
		out.RawString(prefix)
		if in.Head == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Head))
		}
	}
	{
		const prefix string = ",\"bottle\":"
		out.RawString(prefix)
		out.Bool(bool(in.Bottle))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Versions) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Versions) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Versions) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Versions) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV1(l, v)
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV11(in *jlexer.Lexer, out *RuntimeDependency) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "full_name":
			out.FullName = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "revision":
			out.Revision = int(in.Int())
		case "pkg_version":
			out.PkgVersionValue = string(in.String())
		case "declared_directly":
			out.DeclaredDirectly = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV11(out *jwriter.Writer, in RuntimeDependency) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"full_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.FullName))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"revision\":"
		out.RawString(prefix)
		out.Int(int(in.Revision))
	}
	{
		const prefix string = ",\"pkg_version\":"
		out.RawString(prefix)
		out.String(string(in.PkgVersionValue))
	}
	{
		const prefix string = ",\"declared_directly\":"
		out.RawString(prefix)
		out.Bool(bool(in.DeclaredDirectly))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RuntimeDependency) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RuntimeDependency) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RuntimeDependency) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RuntimeDependency) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV11(l, v)
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV12(in *jlexer.Lexer, out *Requirement) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "cask":
			if m, ok := out.Cask.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Cask.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Cask = in.Interface()
			}
		case "download":
			if m, ok := out.Download.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Download.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Download = in.Interface()
			}
		case "version":
			out.Version = string(in.String())
		case "contexts":
			if in.IsNull() {
				in.Skip()
				out.Contexts = nil
			} else {
				in.Delim('[')
				if out.Contexts == nil {
					if !in.IsDelim(']') {
						out.Contexts = make([]string, 0, 4)
					} else {
						out.Contexts = []string{}
					}
				} else {
					out.Contexts = (out.Contexts)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					v3 = string(in.String())
					out.Contexts = append(out.Contexts, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "specs":
			if in.IsNull() {
				in.Skip()
				out.Specs = nil
			} else {
				in.Delim('[')
				if out.Specs == nil {
					if !in.IsDelim(']') {
						out.Specs = make([]string, 0, 4)
					} else {
						out.Specs = []string{}
					}
				} else {
					out.Specs = (out.Specs)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.Specs = append(out.Specs, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV12(out *jwriter.Writer, in Requirement) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"cask\":"
		out.RawString(prefix)
		if m, ok := in.Cask.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Cask.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Cask))
		}
	}
	{
		const prefix string = ",\"download\":"
		out.RawString(prefix)
		if m, ok := in.Download.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Download.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Download))
		}
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"contexts\":"
		out.RawString(prefix)
		if in.Contexts == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Contexts {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"specs\":"
		out.RawString(prefix)
		if in.Specs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Specs {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Requirement) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Requirement) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Requirement) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Requirement) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV12(l, v)
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV13(in *jlexer.Lexer, out *PlatformInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "full_name":
			out.FullName = string(in.String())
		case "tap":
			out.Tap = string(in.String())
		case "oldname":
			out.OldName = string(in.String())
		case "oldnames":
			if in.IsNull() {
				in.Skip()
				out.OldNames = nil
			} else {
				in.Delim('[')
				if out.OldNames == nil {
					if !in.IsDelim(']') {
						out.OldNames = make([]string, 0, 4)
					} else {
						out.OldNames = []string{}
					}
				} else {
					out.OldNames = (out.OldNames)[:0]
				}
				for !in.IsDelim(']') {
					var v9 string
					v9 = string(in.String())
					out.OldNames = append(out.OldNames, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "aliases":
			if in.IsNull() {
				in.Skip()
				out.Aliases = nil
			} else {
				in.Delim('[')
				if out.Aliases == nil {
					if !in.IsDelim(']') {
						out.Aliases = make([]string, 0, 4)
					} else {
						out.Aliases = []string{}
					}
				} else {
					out.Aliases = (out.Aliases)[:0]
				}
				for !in.IsDelim(']') {
					var v10 string
					v10 = string(in.String())
					out.Aliases = append(out.Aliases, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "versioned_formulae":
			if in.IsNull() {
				in.Skip()
				out.VersionedFormulae = nil
			} else {
				in.Delim('[')
				if out.VersionedFormulae == nil {
					if !in.IsDelim(']') {
						out.VersionedFormulae = make([]string, 0, 4)
					} else {
						out.VersionedFormulae = []string{}
					}
				} else {
					out.VersionedFormulae = (out.VersionedFormulae)[:0]
				}
				for !in.IsDelim(']') {
					var v11 string
					v11 = string(in.String())
					out.VersionedFormulae = append(out.VersionedFormulae, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "desc":
			out.Desc = string(in.String())
		case "license":
			out.License = string(in.String())
		case "homepage":
			out.Homepage = string(in.String())
		case "versions":
			(out.Versions).UnmarshalEasyJSON(in)
		case "urls":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.URLs = make(map[string]FormulaURL)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v12 FormulaURL
					(v12).UnmarshalEasyJSON(in)
					(out.URLs)[key] = v12
					in.WantComma()
				}
				in.Delim('}')
			}
		case "revision":
			out.Revision = int(in.Int())
		case "version_scheme":
			out.VersionScheme = int(in.Int())
		case "bottle":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Bottle = make(map[string]*Bottle)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v13 *Bottle
					if in.IsNull() {
						in.Skip()
						v13 = nil
					} else {
						if v13 == nil {
							v13 = new(Bottle)
						}
						(*v13).UnmarshalEasyJSON(in)
					}
					(out.Bottle)[key] = v13
					in.WantComma()
				}
				in.Delim('}')
			}
		case "pour_bottle_only_if":
			if in.IsNull() {
				in.Skip()
				out.PourBottleOnlyIf = nil
			} else {
				if out.PourBottleOnlyIf == nil {
					out.PourBottleOnlyIf = new(string)
				}
				*out.PourBottleOnlyIf = string(in.String())
			}
		case "keg_only":
			out.KegOnly = bool(in.Bool())
		case "keg_only_reason":
			easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon(in, &out.KegOnlyReason)
		case "options":
			if in.IsNull() {
				in.Skip()
				out.Options = nil
			} else {
				in.Delim('[')
				if out.Options == nil {
					if !in.IsDelim(']') {
						out.Options = make([]interface{}, 0, 4)
					} else {
						out.Options = []interface{}{}
					}
				} else {
					out.Options = (out.Options)[:0]
				}
				for !in.IsDelim(']') {
					var v14 interface{}
					if m, ok := v14.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v14.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v14 = in.Interface()
					}
					out.Options = append(out.Options, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "build_dependencies":
			if in.IsNull() {
				in.Skip()
				out.BuildDependencies = nil
			} else {
				in.Delim('[')
				if out.BuildDependencies == nil {
					if !in.IsDelim(']') {
						out.BuildDependencies = make([]string, 0, 4)
					} else {
						out.BuildDependencies = []string{}
					}
				} else {
					out.BuildDependencies = (out.BuildDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v15 string
					v15 = string(in.String())
					out.BuildDependencies = append(out.BuildDependencies, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "dependencies":
			if in.IsNull() {
				in.Skip()
				out.Dependencies = nil
			} else {
				in.Delim('[')
				if out.Dependencies == nil {
					if !in.IsDelim(']') {
						out.Dependencies = make([]string, 0, 4)
					} else {
						out.Dependencies = []string{}
					}
				} else {
					out.Dependencies = (out.Dependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v16 string
					v16 = string(in.String())
					out.Dependencies = append(out.Dependencies, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "test_dependencies":
			if in.IsNull() {
				in.Skip()
				out.TestDependencies = nil
			} else {
				in.Delim('[')
				if out.TestDependencies == nil {
					if !in.IsDelim(']') {
						out.TestDependencies = make([]string, 0, 4)
					} else {
						out.TestDependencies = []string{}
					}
				} else {
					out.TestDependencies = (out.TestDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v17 string
					v17 = string(in.String())
					out.TestDependencies = append(out.TestDependencies, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "recommended_dependencies":
			if in.IsNull() {
				in.Skip()
				out.RecommendedDependencies = nil
			} else {
				in.Delim('[')
				if out.RecommendedDependencies == nil {
					if !in.IsDelim(']') {
						out.RecommendedDependencies = make([]string, 0, 4)
					} else {
						out.RecommendedDependencies = []string{}
					}
				} else {
					out.RecommendedDependencies = (out.RecommendedDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v18 string
					v18 = string(in.String())
					out.RecommendedDependencies = append(out.RecommendedDependencies, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "optional_dependencies":
			if in.IsNull() {
				in.Skip()
				out.OptionalDependencies = nil
			} else {
				in.Delim('[')
				if out.OptionalDependencies == nil {
					if !in.IsDelim(']') {
						out.OptionalDependencies = make([]string, 0, 4)
					} else {
						out.OptionalDependencies = []string{}
					}
				} else {
					out.OptionalDependencies = (out.OptionalDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v19 string
					v19 = string(in.String())
					out.OptionalDependencies = append(out.OptionalDependencies, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "uses_from_macos":
			if in.IsNull() {
				in.Skip()
				out.UsesFromMacOS = nil
			} else {
				in.Delim('[')
				if out.UsesFromMacOS == nil {
					if !in.IsDelim(']') {
						out.UsesFromMacOS = make([]interface{}, 0, 4)
					} else {
						out.UsesFromMacOS = []interface{}{}
					}
				} else {
					out.UsesFromMacOS = (out.UsesFromMacOS)[:0]
				}
				for !in.IsDelim(']') {
					var v20 interface{}
					if m, ok := v20.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v20.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v20 = in.Interface()
					}
					out.UsesFromMacOS = append(out.UsesFromMacOS, v20)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "uses_from_macos_bounds":
			if in.IsNull() {
				in.Skip()
				out.UsesFromMacOSBounds = nil
			} else {
				in.Delim('[')
				if out.UsesFromMacOSBounds == nil {
					if !in.IsDelim(']') {
						out.UsesFromMacOSBounds = make([]*MacOSBounds, 0, 8)
					} else {
						out.UsesFromMacOSBounds = []*MacOSBounds{}
					}
				} else {
					out.UsesFromMacOSBounds = (out.UsesFromMacOSBounds)[:0]
				}
				for !in.IsDelim(']') {
					var v21 *MacOSBounds
					if in.IsNull() {
						in.Skip()
						v21 = nil
					} else {
						if v21 == nil {
							v21 = new(MacOSBounds)
						}
						(*v21).UnmarshalEasyJSON(in)
					}
					out.UsesFromMacOSBounds = append(out.UsesFromMacOSBounds, v21)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "requirements":
			if in.IsNull() {
				in.Skip()
				out.Requirements = nil
			} else {
				in.Delim('[')
				if out.Requirements == nil {
					if !in.IsDelim(']') {
						out.Requirements = make([]*Requirement, 0, 8)
					} else {
						out.Requirements = []*Requirement{}
					}
				} else {
					out.Requirements = (out.Requirements)[:0]
				}
				for !in.IsDelim(']') {
					var v22 *Requirement
					if in.IsNull() {
						in.Skip()
						v22 = nil
					} else {
						if v22 == nil {
							v22 = new(Requirement)
						}
						(*v22).UnmarshalEasyJSON(in)
					}
					out.Requirements = append(out.Requirements, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "conflicts_with":
			if in.IsNull() {
				in.Skip()
				out.ConflictsWith = nil
			} else {
				in.Delim('[')
				if out.ConflictsWith == nil {
					if !in.IsDelim(']') {
						out.ConflictsWith = make([]string, 0, 4)
					} else {
						out.ConflictsWith = []string{}
					}
				} else {
					out.ConflictsWith = (out.ConflictsWith)[:0]
				}
				for !in.IsDelim(']') {
					var v23 string
					v23 = string(in.String())
					out.ConflictsWith = append(out.ConflictsWith, v23)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "conflicts_with_reasons":
			if in.IsNull() {
				in.Skip()
				out.ConflictsWithReasons = nil
			} else {
				in.Delim('[')
				if out.ConflictsWithReasons == nil {
					if !in.IsDelim(']') {
						out.ConflictsWithReasons = make([]string, 0, 4)
					} else {
						out.ConflictsWithReasons = []string{}
					}
				} else {
					out.ConflictsWithReasons = (out.ConflictsWithReasons)[:0]
				}
				for !in.IsDelim(']') {
					var v24 string
					v24 = string(in.String())
					out.ConflictsWithReasons = append(out.ConflictsWithReasons, v24)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "link_overwrite":
			if in.IsNull() {
				in.Skip()
				out.LinkOverwrite = nil
			} else {
				in.Delim('[')
				if out.LinkOverwrite == nil {
					if !in.IsDelim(']') {
						out.LinkOverwrite = make([]string, 0, 4)
					} else {
						out.LinkOverwrite = []string{}
					}
				} else {
					out.LinkOverwrite = (out.LinkOverwrite)[:0]
				}
				for !in.IsDelim(']') {
					var v25 string
					v25 = string(in.String())
					out.LinkOverwrite = append(out.LinkOverwrite, v25)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "caveats":
			if in.IsNull() {
				in.Skip()
				out.Caveats = nil
			} else {
				if out.Caveats == nil {
					out.Caveats = new(string)
				}
				*out.Caveats = string(in.String())
			}
		case "installed":
			if in.IsNull() {
				in.Skip()
				out.Installed = nil
			} else {
				in.Delim('[')
				if out.Installed == nil {
					if !in.IsDelim(']') {
						out.Installed = make([]InstalledInfo, 0, 0)
					} else {
						out.Installed = []InstalledInfo{}
					}
				} else {
					out.Installed = (out.Installed)[:0]
				}
				for !in.IsDelim(']') {
					var v26 InstalledInfo
					(v26).UnmarshalEasyJSON(in)
					out.Installed = append(out.Installed, v26)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "linked_keg":
			out.LinkedKeg = string(in.String())
		case "pinned":
			out.Pinned = bool(in.Bool())
		case "outdated":
			out.Outdated = bool(in.Bool())
		case "deprecated":
			out.Deprecated = bool(in.Bool())
		case "deprecation_date":
			if in.IsNull() {
				in.Skip()
				out.DeprecationDate = nil
			} else {
				if out.DeprecationDate == nil {
					out.DeprecationDate = new(string)
				}
				*out.DeprecationDate = string(in.String())
			}
		case "deprecation_reason":
			if in.IsNull() {
				in.Skip()
				out.DeprecationReason = nil
			} else {
				if out.DeprecationReason == nil {
					out.DeprecationReason = new(string)
				}
				*out.DeprecationReason = string(in.String())
			}
		case "disabled":
			out.Disabled = bool(in.Bool())
		case "disable_date":
			if in.IsNull() {
				in.Skip()
				out.DisabledDate = nil
			} else {
				if out.DisabledDate == nil {
					out.DisabledDate = new(string)
				}
				*out.DisabledDate = string(in.String())
			}
		case "disable_reason":
			if in.IsNull() {
				in.Skip()
				out.DisabledReason = nil
			} else {
				if out.DisabledReason == nil {
					out.DisabledReason = new(string)
				}
				*out.DisabledReason = string(in.String())
			}
		case "post_install_defined":
			out.PostInstallDefined = bool(in.Bool())
		case "service":
			if in.IsNull() {
				in.Skip()
				out.Service = nil
			} else {
				if out.Service == nil {
					out.Service = new(common.Service)
				}
				easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon1(in, out.Service)
			}
		case "tap_git_head":
			out.TapGitHead = string(in.String())
		case "ruby_source_path":
			out.RubySourcePath = string(in.String())
		case "ruby_source_checksum":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.RubySourceChecksum = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v27 string
					v27 = string(in.String())
					(out.RubySourceChecksum)[key] = v27
					in.WantComma()
				}
				in.Delim('}')
			}
		case "head_dependencies":
			if in.IsNull() {
				in.Skip()
				out.HeadDependencies = nil
			} else {
				if out.HeadDependencies == nil {
					out.HeadDependencies = new(HeadDependencies)
				}
				(*out.HeadDependencies).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV13(out *jwriter.Writer, in PlatformInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"full_name\":"
		out.RawString(prefix)
		out.String(string(in.FullName))
	}
	{
		const prefix string = ",\"tap\":"
		out.RawString(prefix)
		out.String(string(in.Tap))
	}
	{
		const prefix string = ",\"oldname\":"
		out.RawString(prefix)
		out.String(string(in.OldName))
	}
	{
		const prefix string = ",\"oldnames\":"
		out.RawString(prefix)
		if in.OldNames == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v28, v29 := range in.OldNames {
				if v28 > 0 {
					out.RawByte(',')
				}
				out.String(string(v29))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"aliases\":"
		out.RawString(prefix)
		if in.Aliases == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v30, v31 := range in.Aliases {
				if v30 > 0 {
					out.RawByte(',')
				}
				out.String(string(v31))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"versioned_formulae\":"
		out.RawString(prefix)
		if in.VersionedFormulae == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v32, v33 := range in.VersionedFormulae {
				if v32 > 0 {
					out.RawByte(',')
				}
				out.String(string(v33))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"desc\":"
		out.RawString(prefix)
		out.String(string(in.Desc))
	}
	{
		const prefix string = ",\"license\":"
		out.RawString(prefix)
		out.String(string(in.License))
	}
	{
		const prefix string = ",\"homepage\":"
		out.RawString(prefix)
		out.String(string(in.Homepage))
	}
	{
		const prefix string = ",\"versions\":"
		out.RawString(prefix)
		(in.Versions).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"urls\":"
		out.RawString(prefix)
		if in.URLs == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v34First := true
			for v34Name, v34Value := range in.URLs {
				if v34First {
					v34First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v34Name))
				out.RawByte(':')
				(v34Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"revision\":"
		out.RawString(prefix)
		out.Int(int(in.Revision))
	}
	{
		const prefix string = ",\"version_scheme\":"
		out.RawString(prefix)
		out.Int(int(in.VersionScheme))
	}
	{
		const prefix string = ",\"bottle\":"
		out.RawString(prefix)
		if in.Bottle == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v35First := true
			for v35Name, v35Value := range in.Bottle {
				if v35First {
					v35First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v35Name))
				out.RawByte(':')
				if v35Value == nil {
					out.RawString("null")
				} else {
					(*v35Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"pour_bottle_only_if\":"
		out.RawString(prefix)
		if in.PourBottleOnlyIf == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PourBottleOnlyIf))
		}
	}
	{
		const prefix string = ",\"keg_only\":"
		out.RawString(prefix)
		out.Bool(bool(in.KegOnly))
	}
	{
		const prefix string = ",\"keg_only_reason\":"
		out.RawString(prefix)
		easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon(out, in.KegOnlyReason)
	}
	{
		const prefix string = ",\"options\":"
		out.RawString(prefix)
		if in.Options == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v36, v37 := range in.Options {
				if v36 > 0 {
					out.RawByte(',')
				}
				if m, ok := v37.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v37.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v37))
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"build_dependencies\":"
		out.RawString(prefix)
		if in.BuildDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v38, v39 := range in.BuildDependencies {
				if v38 > 0 {
					out.RawByte(',')
				}
				out.String(string(v39))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"dependencies\":"
		out.RawString(prefix)
		if in.Dependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v40, v41 := range in.Dependencies {
				if v40 > 0 {
					out.RawByte(',')
				}
				out.String(string(v41))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"test_dependencies\":"
		out.RawString(prefix)
		if in.TestDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v42, v43 := range in.TestDependencies {
				if v42 > 0 {
					out.RawByte(',')
				}
				out.String(string(v43))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"recommended_dependencies\":"
		out.RawString(prefix)
		if in.RecommendedDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v44, v45 := range in.RecommendedDependencies {
				if v44 > 0 {
					out.RawByte(',')
				}
				out.String(string(v45))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"optional_dependencies\":"
		out.RawString(prefix)
		if in.OptionalDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v46, v47 := range in.OptionalDependencies {
				if v46 > 0 {
					out.RawByte(',')
				}
				out.String(string(v47))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"uses_from_macos\":"
		out.RawString(prefix)
		if in.UsesFromMacOS == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v48, v49 := range in.UsesFromMacOS {
				if v48 > 0 {
					out.RawByte(',')
				}
				if m, ok := v49.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v49.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v49))
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"uses_from_macos_bounds\":"
		out.RawString(prefix)
		if in.UsesFromMacOSBounds == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v50, v51 := range in.UsesFromMacOSBounds {
				if v50 > 0 {
					out.RawByte(',')
				}
				if v51 == nil {
					out.RawString("null")
				} else {
					(*v51).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"requirements\":"
		out.RawString(prefix)
		if in.Requirements == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v52, v53 := range in.Requirements {
				if v52 > 0 {
					out.RawByte(',')
				}
				if v53 == nil {
					out.RawString("null")
				} else {
					(*v53).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"conflicts_with\":"
		out.RawString(prefix)
		if in.ConflictsWith == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v54, v55 := range in.ConflictsWith {
				if v54 > 0 {
					out.RawByte(',')
				}
				out.String(string(v55))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"conflicts_with_reasons\":"
		out.RawString(prefix)
		if in.ConflictsWithReasons == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v56, v57 := range in.ConflictsWithReasons {
				if v56 > 0 {
					out.RawByte(',')
				}
				out.String(string(v57))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"link_overwrite\":"
		out.RawString(prefix)
		if in.LinkOverwrite == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v58, v59 := range in.LinkOverwrite {
				if v58 > 0 {
					out.RawByte(',')
				}
				out.String(string(v59))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"caveats\":"
		out.RawString(prefix)
		if in.Caveats == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Caveats))
		}
	}
	{
		const prefix string = ",\"installed\":"
		out.RawString(prefix)
		if in.Installed == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v60, v61 := range in.Installed {
				if v60 > 0 {
					out.RawByte(',')
				}
				(v61).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"linked_keg\":"
		out.RawString(prefix)
		out.String(string(in.LinkedKeg))
	}
	{
		const prefix string = ",\"pinned\":"
		out.RawString(prefix)
		out.Bool(bool(in.Pinned))
	}
	{
		const prefix string = ",\"outdated\":"
		out.RawString(prefix)
		out.Bool(bool(in.Outdated))
	}
	{
		const prefix string = ",\"deprecated\":"
		out.RawString(prefix)
		out.Bool(bool(in.Deprecated))
	}
	{
		const prefix string = ",\"deprecation_date\":"
		out.RawString(prefix)
		if in.DeprecationDate == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DeprecationDate))
		}
	}
	{
		const prefix string = ",\"deprecation_reason\":"
		out.RawString(prefix)
		if in.DeprecationReason == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DeprecationReason))
		}
	}
	{
		const prefix string = ",\"disabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Disabled))
	}
	{
		const prefix string = ",\"disable_date\":"
		out.RawString(prefix)
		if in.DisabledDate == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DisabledDate))
		}
	}
	{
		const prefix string = ",\"disable_reason\":"
		out.RawString(prefix)
		if in.DisabledReason == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DisabledReason))
		}
	}
	{
		const prefix string = ",\"post_install_defined\":"
		out.RawString(prefix)
		out.Bool(bool(in.PostInstallDefined))
	}
	{
		const prefix string = ",\"service\":"
		out.RawString(prefix)
		if in.Service == nil {
			out.RawString("null")
		} else {
			easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon1(out, *in.Service)
		}
	}
	{
		const prefix string = ",\"tap_git_head\":"
		out.RawString(prefix)
		out.String(string(in.TapGitHead))
	}
	{
		const prefix string = ",\"ruby_source_path\":"
		out.RawString(prefix)
		out.String(string(in.RubySourcePath))
	}
	{
		const prefix string = ",\"ruby_source_checksum\":"
		out.RawString(prefix)
		if in.RubySourceChecksum == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v62First := true
			for v62Name, v62Value := range in.RubySourceChecksum {
				if v62First {
					v62First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v62Name))
				out.RawByte(':')
				out.String(string(v62Value))
			}
			out.RawByte('}')
		}
	}
	if in.HeadDependencies != nil {
		const prefix string = ",\"head_dependencies\":"
		out.RawString(prefix)
		(*in.HeadDependencies).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PlatformInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PlatformInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PlatformInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PlatformInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV13(l, v)
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon1(in *jlexer.Lexer, out *common.Service) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Name = make(map[string]string)
				} else {
					out.Name = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v63 string
					v63 = string(in.String())
					(out.Name)[key] = v63
					in.WantComma()
				}
				in.Delim('}')
			}
		case "run":
			if m, ok := out.Run.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Run.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Run = in.Interface()
			}
		case "run_type":
			out.RunType = common.ServiceRunType(in.String())
		case "environment_variables":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.EnvironmentVariables = make(map[string]string)
				} else {
					out.EnvironmentVariables = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v64 string
					v64 = string(in.String())
					(out.EnvironmentVariables)[key] = v64
					in.WantComma()
				}
				in.Delim('}')
			}
		case "interval":
			out.Interval = time.Duration(in.Int64())
		case "cron":
			out.Cron = string(in.String())
		case "require_root":
			out.RequireRoot = bool(in.Bool())
		case "keep_alive":
			easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon2(in, &out.KeepAlive)
		case "working_dir":
			out.WorkingDir = string(in.String())
		case "input_path":
			out.InputPath = string(in.String())
		case "log_path":
			out.LogPath = string(in.String())
		case "error_log_path":
			out.ErrorLogPath = string(in.String())
		case "sockets":
			out.Sockets = string(in.String())
		case "process_type":
			out.ProcessType = common.ProcessType(in.String())
		case "macos_legacy_timers":
			out.MacOSLegacyTimers = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon1(out *jwriter.Writer, in common.Service) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Name) != 0 {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('{')
			v65First := true
			for v65Name, v65Value := range in.Name {
				if v65First {
					v65First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v65Name))
				out.RawByte(':')
				out.String(string(v65Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"run\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.Run.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Run.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Run))
		}
	}
	{
		const prefix string = ",\"run_type\":"
		out.RawString(prefix)
		out.String(string(in.RunType))
	}
	if len(in.EnvironmentVariables) != 0 {
		const prefix string = ",\"environment_variables\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v66First := true
			for v66Name, v66Value := range in.EnvironmentVariables {
				if v66First {
					v66First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v66Name))
				out.RawByte(':')
				out.String(string(v66Value))
			}
			out.RawByte('}')
		}
	}
	if in.Interval != 0 {
		const prefix string = ",\"interval\":"
		out.RawString(prefix)
		out.Int64(int64(in.Interval))
	}
	if in.Cron != "" {
		const prefix string = ",\"cron\":"
		out.RawString(prefix)
		out.String(string(in.Cron))
	}
	if in.RequireRoot {
		const prefix string = ",\"require_root\":"
		out.RawString(prefix)
		out.Bool(bool(in.RequireRoot))
	}
	if true {
		const prefix string = ",\"keep_alive\":"
		out.RawString(prefix)
		easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon2(out, in.KeepAlive)
	}
	if in.WorkingDir != "" {
		const prefix string = ",\"working_dir\":"
		out.RawString(prefix)
		out.String(string(in.WorkingDir))
	}
	if in.InputPath != "" {
		const prefix string = ",\"input_path\":"
		out.RawString(prefix)
		out.String(string(in.InputPath))
	}
	if in.LogPath != "" {
		const prefix string = ",\"log_path\":"
		out.RawString(prefix)
		out.String(string(in.LogPath))
	}
	if in.ErrorLogPath != "" {
		const prefix string = ",\"error_log_path\":"
		out.RawString(prefix)
		out.String(string(in.ErrorLogPath))
	}
	if in.Sockets != "" {
		const prefix string = ",\"sockets\":"
		out.RawString(prefix)
		out.String(string(in.Sockets))
	}
	if in.ProcessType != "" {
		const prefix string = ",\"process_type\":"
		out.RawString(prefix)
		out.String(string(in.ProcessType))
	}
	if in.MacOSLegacyTimers {
		const prefix string = ",\"macos_legacy_timers\":"
		out.RawString(prefix)
		out.Bool(bool(in.MacOSLegacyTimers))
	}
	out.RawByte('}')
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon2(in *jlexer.Lexer, out *common.KeepAliveConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "always":
			out.Always = bool(in.Bool())
		case "successful_exit":
			out.SuccessfulExit = bool(in.Bool())
		case "crashed":
			out.Crashed = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon2(out *jwriter.Writer, in common.KeepAliveConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Always {
		const prefix string = ",\"always\":"
		first = false
		out.RawString(prefix[1:])
		out.Bool(bool(in.Always))
	}
	if in.SuccessfulExit {
		const prefix string = ",\"successful_exit\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.SuccessfulExit))
	}
	if in.Crashed {
		const prefix string = ",\"crashed\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Crashed))
	}
	out.RawByte('}')
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon(in *jlexer.Lexer, out *common.KegOnlyConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "reason":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Reason).UnmarshalJSON(data))
			}
		case "explanation":
			out.Explanation = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon(out *jwriter.Writer, in common.KegOnlyConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Reason != "" {
		const prefix string = ",\"reason\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((in.Reason).MarshalJSON())
	}
	if in.Explanation != "" {
		const prefix string = ",\"explanation\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Explanation))
	}
	out.RawByte('}')
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV14(in *jlexer.Lexer, out *MacOSBounds) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "since":
			out.Since = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV14(out *jwriter.Writer, in MacOSBounds) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"since\":"
		out.RawString(prefix[1:])
		out.String(string(in.Since))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MacOSBounds) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MacOSBounds) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MacOSBounds) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MacOSBounds) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV14(l, v)
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV15(in *jlexer.Lexer, out *InstalledInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "version":
			out.Version = string(in.String())
		case "used_options":
			if in.IsNull() {
				in.Skip()
				out.UsedOptions = nil
			} else {
				in.Delim('[')
				if out.UsedOptions == nil {
					if !in.IsDelim(']') {
						out.UsedOptions = make([]interface{}, 0, 4)
					} else {
						out.UsedOptions = []interface{}{}
					}
				} else {
					out.UsedOptions = (out.UsedOptions)[:0]
				}
				for !in.IsDelim(']') {
					var v67 interface{}
					if m, ok := v67.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v67.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v67 = in.Interface()
					}
					out.UsedOptions = append(out.UsedOptions, v67)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "built_as_bottle":
			out.BuiltAsBottle = bool(in.Bool())
		case "poured_from_bottle":
			out.PouredFromBottle = bool(in.Bool())
		case "time":
			out.Time = int(in.Int())
		case "runtime_dependencies":
			if in.IsNull() {
				in.Skip()
				out.RuntimeDependencies = nil
			} else {
				in.Delim('[')
				if out.RuntimeDependencies == nil {
					if !in.IsDelim(']') {
						out.RuntimeDependencies = make([]*RuntimeDependency, 0, 8)
					} else {
						out.RuntimeDependencies = []*RuntimeDependency{}
					}
				} else {
					out.RuntimeDependencies = (out.RuntimeDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v68 *RuntimeDependency
					if in.IsNull() {
						in.Skip()
						v68 = nil
					} else {
						if v68 == nil {
							v68 = new(RuntimeDependency)
						}
						(*v68).UnmarshalEasyJSON(in)
					}
					out.RuntimeDependencies = append(out.RuntimeDependencies, v68)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "installed_as_dependency":
			out.InstalledAsDependency = bool(in.Bool())
		case "installed_on_request":
			out.InstalledOnRequest = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV15(out *jwriter.Writer, in InstalledInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix[1:])
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"used_options\":"
		out.RawString(prefix)
		if in.UsedOptions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v69, v70 := range in.UsedOptions {
				if v69 > 0 {
					out.RawByte(',')
				}
				if m, ok := v70.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v70.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v70))
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"built_as_bottle\":"
		out.RawString(prefix)
		out.Bool(bool(in.BuiltAsBottle))
	}
	{
		const prefix string = ",\"poured_from_bottle\":"
		out.RawString(prefix)
		out.Bool(bool(in.PouredFromBottle))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Int(int(in.Time))
	}
	{
		const prefix string = ",\"runtime_dependencies\":"
		out.RawString(prefix)
		if in.RuntimeDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v71, v72 := range in.RuntimeDependencies {
				if v71 > 0 {
					out.RawByte(',')
				}
				if v72 == nil {
					out.RawString("null")
				} else {
					(*v72).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"installed_as_dependency\":"
		out.RawString(prefix)
		out.Bool(bool(in.InstalledAsDependency))
	}
	{
		const prefix string = ",\"installed_on_request\":"
		out.RawString(prefix)
		out.Bool(bool(in.InstalledOnRequest))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InstalledInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InstalledInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InstalledInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InstalledInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV15(l, v)
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV16(in *jlexer.Lexer, out *Info) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "variations":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Variations = make(map[platform.Platform]*PlatformInfo)
				for !in.IsDelim('}') {
					key := platform.Platform(in.String())
					in.WantColon()
					var v73 *PlatformInfo
					if in.IsNull() {
						in.Skip()
						v73 = nil
					} else {
						if v73 == nil {
							v73 = new(PlatformInfo)
						}
						(*v73).UnmarshalEasyJSON(in)
					}
					(out.Variations)[key] = v73
					in.WantComma()
				}
				in.Delim('}')
			}
		case "name":
			out.Name = string(in.String())
		case "full_name":
			out.FullName = string(in.String())
		case "tap":
			out.Tap = string(in.String())
		case "oldname":
			out.OldName = string(in.String())
		case "oldnames":
			if in.IsNull() {
				in.Skip()
				out.OldNames = nil
			} else {
				in.Delim('[')
				if out.OldNames == nil {
					if !in.IsDelim(']') {
						out.OldNames = make([]string, 0, 4)
					} else {
						out.OldNames = []string{}
					}
				} else {
					out.OldNames = (out.OldNames)[:0]
				}
				for !in.IsDelim(']') {
					var v74 string
					v74 = string(in.String())
					out.OldNames = append(out.OldNames, v74)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "aliases":
			if in.IsNull() {
				in.Skip()
				out.Aliases = nil
			} else {
				in.Delim('[')
				if out.Aliases == nil {
					if !in.IsDelim(']') {
						out.Aliases = make([]string, 0, 4)
					} else {
						out.Aliases = []string{}
					}
				} else {
					out.Aliases = (out.Aliases)[:0]
				}
				for !in.IsDelim(']') {
					var v75 string
					v75 = string(in.String())
					out.Aliases = append(out.Aliases, v75)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "versioned_formulae":
			if in.IsNull() {
				in.Skip()
				out.VersionedFormulae = nil
			} else {
				in.Delim('[')
				if out.VersionedFormulae == nil {
					if !in.IsDelim(']') {
						out.VersionedFormulae = make([]string, 0, 4)
					} else {
						out.VersionedFormulae = []string{}
					}
				} else {
					out.VersionedFormulae = (out.VersionedFormulae)[:0]
				}
				for !in.IsDelim(']') {
					var v76 string
					v76 = string(in.String())
					out.VersionedFormulae = append(out.VersionedFormulae, v76)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "desc":
			out.Desc = string(in.String())
		case "license":
			out.License = string(in.String())
		case "homepage":
			out.Homepage = string(in.String())
		case "versions":
			(out.Versions).UnmarshalEasyJSON(in)
		case "urls":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.URLs = make(map[string]FormulaURL)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v77 FormulaURL
					(v77).UnmarshalEasyJSON(in)
					(out.URLs)[key] = v77
					in.WantComma()
				}
				in.Delim('}')
			}
		case "revision":
			out.Revision = int(in.Int())
		case "version_scheme":
			out.VersionScheme = int(in.Int())
		case "bottle":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Bottle = make(map[string]*Bottle)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v78 *Bottle
					if in.IsNull() {
						in.Skip()
						v78 = nil
					} else {
						if v78 == nil {
							v78 = new(Bottle)
						}
						(*v78).UnmarshalEasyJSON(in)
					}
					(out.Bottle)[key] = v78
					in.WantComma()
				}
				in.Delim('}')
			}
		case "pour_bottle_only_if":
			if in.IsNull() {
				in.Skip()
				out.PourBottleOnlyIf = nil
			} else {
				if out.PourBottleOnlyIf == nil {
					out.PourBottleOnlyIf = new(string)
				}
				*out.PourBottleOnlyIf = string(in.String())
			}
		case "keg_only":
			out.KegOnly = bool(in.Bool())
		case "keg_only_reason":
			easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon(in, &out.KegOnlyReason)
		case "options":
			if in.IsNull() {
				in.Skip()
				out.Options = nil
			} else {
				in.Delim('[')
				if out.Options == nil {
					if !in.IsDelim(']') {
						out.Options = make([]interface{}, 0, 4)
					} else {
						out.Options = []interface{}{}
					}
				} else {
					out.Options = (out.Options)[:0]
				}
				for !in.IsDelim(']') {
					var v79 interface{}
					if m, ok := v79.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v79.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v79 = in.Interface()
					}
					out.Options = append(out.Options, v79)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "build_dependencies":
			if in.IsNull() {
				in.Skip()
				out.BuildDependencies = nil
			} else {
				in.Delim('[')
				if out.BuildDependencies == nil {
					if !in.IsDelim(']') {
						out.BuildDependencies = make([]string, 0, 4)
					} else {
						out.BuildDependencies = []string{}
					}
				} else {
					out.BuildDependencies = (out.BuildDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v80 string
					v80 = string(in.String())
					out.BuildDependencies = append(out.BuildDependencies, v80)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "dependencies":
			if in.IsNull() {
				in.Skip()
				out.Dependencies = nil
			} else {
				in.Delim('[')
				if out.Dependencies == nil {
					if !in.IsDelim(']') {
						out.Dependencies = make([]string, 0, 4)
					} else {
						out.Dependencies = []string{}
					}
				} else {
					out.Dependencies = (out.Dependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v81 string
					v81 = string(in.String())
					out.Dependencies = append(out.Dependencies, v81)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "test_dependencies":
			if in.IsNull() {
				in.Skip()
				out.TestDependencies = nil
			} else {
				in.Delim('[')
				if out.TestDependencies == nil {
					if !in.IsDelim(']') {
						out.TestDependencies = make([]string, 0, 4)
					} else {
						out.TestDependencies = []string{}
					}
				} else {
					out.TestDependencies = (out.TestDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v82 string
					v82 = string(in.String())
					out.TestDependencies = append(out.TestDependencies, v82)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "recommended_dependencies":
			if in.IsNull() {
				in.Skip()
				out.RecommendedDependencies = nil
			} else {
				in.Delim('[')
				if out.RecommendedDependencies == nil {
					if !in.IsDelim(']') {
						out.RecommendedDependencies = make([]string, 0, 4)
					} else {
						out.RecommendedDependencies = []string{}
					}
				} else {
					out.RecommendedDependencies = (out.RecommendedDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v83 string
					v83 = string(in.String())
					out.RecommendedDependencies = append(out.RecommendedDependencies, v83)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "optional_dependencies":
			if in.IsNull() {
				in.Skip()
				out.OptionalDependencies = nil
			} else {
				in.Delim('[')
				if out.OptionalDependencies == nil {
					if !in.IsDelim(']') {
						out.OptionalDependencies = make([]string, 0, 4)
					} else {
						out.OptionalDependencies = []string{}
					}
				} else {
					out.OptionalDependencies = (out.OptionalDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v84 string
					v84 = string(in.String())
					out.OptionalDependencies = append(out.OptionalDependencies, v84)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "uses_from_macos":
			if in.IsNull() {
				in.Skip()
				out.UsesFromMacOS = nil
			} else {
				in.Delim('[')
				if out.UsesFromMacOS == nil {
					if !in.IsDelim(']') {
						out.UsesFromMacOS = make([]interface{}, 0, 4)
					} else {
						out.UsesFromMacOS = []interface{}{}
					}
				} else {
					out.UsesFromMacOS = (out.UsesFromMacOS)[:0]
				}
				for !in.IsDelim(']') {
					var v85 interface{}
					if m, ok := v85.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v85.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v85 = in.Interface()
					}
					out.UsesFromMacOS = append(out.UsesFromMacOS, v85)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "uses_from_macos_bounds":
			if in.IsNull() {
				in.Skip()
				out.UsesFromMacOSBounds = nil
			} else {
				in.Delim('[')
				if out.UsesFromMacOSBounds == nil {
					if !in.IsDelim(']') {
						out.UsesFromMacOSBounds = make([]*MacOSBounds, 0, 8)
					} else {
						out.UsesFromMacOSBounds = []*MacOSBounds{}
					}
				} else {
					out.UsesFromMacOSBounds = (out.UsesFromMacOSBounds)[:0]
				}
				for !in.IsDelim(']') {
					var v86 *MacOSBounds
					if in.IsNull() {
						in.Skip()
						v86 = nil
					} else {
						if v86 == nil {
							v86 = new(MacOSBounds)
						}
						(*v86).UnmarshalEasyJSON(in)
					}
					out.UsesFromMacOSBounds = append(out.UsesFromMacOSBounds, v86)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "requirements":
			if in.IsNull() {
				in.Skip()
				out.Requirements = nil
			} else {
				in.Delim('[')
				if out.Requirements == nil {
					if !in.IsDelim(']') {
						out.Requirements = make([]*Requirement, 0, 8)
					} else {
						out.Requirements = []*Requirement{}
					}
				} else {
					out.Requirements = (out.Requirements)[:0]
				}
				for !in.IsDelim(']') {
					var v87 *Requirement
					if in.IsNull() {
						in.Skip()
						v87 = nil
					} else {
						if v87 == nil {
							v87 = new(Requirement)
						}
						(*v87).UnmarshalEasyJSON(in)
					}
					out.Requirements = append(out.Requirements, v87)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "conflicts_with":
			if in.IsNull() {
				in.Skip()
				out.ConflictsWith = nil
			} else {
				in.Delim('[')
				if out.ConflictsWith == nil {
					if !in.IsDelim(']') {
						out.ConflictsWith = make([]string, 0, 4)
					} else {
						out.ConflictsWith = []string{}
					}
				} else {
					out.ConflictsWith = (out.ConflictsWith)[:0]
				}
				for !in.IsDelim(']') {
					var v88 string
					v88 = string(in.String())
					out.ConflictsWith = append(out.ConflictsWith, v88)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "conflicts_with_reasons":
			if in.IsNull() {
				in.Skip()
				out.ConflictsWithReasons = nil
			} else {
				in.Delim('[')
				if out.ConflictsWithReasons == nil {
					if !in.IsDelim(']') {
						out.ConflictsWithReasons = make([]string, 0, 4)
					} else {
						out.ConflictsWithReasons = []string{}
					}
				} else {
					out.ConflictsWithReasons = (out.ConflictsWithReasons)[:0]
				}
				for !in.IsDelim(']') {
					var v89 string
					v89 = string(in.String())
					out.ConflictsWithReasons = append(out.ConflictsWithReasons, v89)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "link_overwrite":
			if in.IsNull() {
				in.Skip()
				out.LinkOverwrite = nil
			} else {
				in.Delim('[')
				if out.LinkOverwrite == nil {
					if !in.IsDelim(']') {
						out.LinkOverwrite = make([]string, 0, 4)
					} else {
						out.LinkOverwrite = []string{}
					}
				} else {
					out.LinkOverwrite = (out.LinkOverwrite)[:0]
				}
				for !in.IsDelim(']') {
					var v90 string
					v90 = string(in.String())
					out.LinkOverwrite = append(out.LinkOverwrite, v90)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "caveats":
			if in.IsNull() {
				in.Skip()
				out.Caveats = nil
			} else {
				if out.Caveats == nil {
					out.Caveats = new(string)
				}
				*out.Caveats = string(in.String())
			}
		case "installed":
			if in.IsNull() {
				in.Skip()
				out.Installed = nil
			} else {
				in.Delim('[')
				if out.Installed == nil {
					if !in.IsDelim(']') {
						out.Installed = make([]InstalledInfo, 0, 0)
					} else {
						out.Installed = []InstalledInfo{}
					}
				} else {
					out.Installed = (out.Installed)[:0]
				}
				for !in.IsDelim(']') {
					var v91 InstalledInfo
					(v91).UnmarshalEasyJSON(in)
					out.Installed = append(out.Installed, v91)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "linked_keg":
			out.LinkedKeg = string(in.String())
		case "pinned":
			out.Pinned = bool(in.Bool())
		case "outdated":
			out.Outdated = bool(in.Bool())
		case "deprecated":
			out.Deprecated = bool(in.Bool())
		case "deprecation_date":
			if in.IsNull() {
				in.Skip()
				out.DeprecationDate = nil
			} else {
				if out.DeprecationDate == nil {
					out.DeprecationDate = new(string)
				}
				*out.DeprecationDate = string(in.String())
			}
		case "deprecation_reason":
			if in.IsNull() {
				in.Skip()
				out.DeprecationReason = nil
			} else {
				if out.DeprecationReason == nil {
					out.DeprecationReason = new(string)
				}
				*out.DeprecationReason = string(in.String())
			}
		case "disabled":
			out.Disabled = bool(in.Bool())
		case "disable_date":
			if in.IsNull() {
				in.Skip()
				out.DisabledDate = nil
			} else {
				if out.DisabledDate == nil {
					out.DisabledDate = new(string)
				}
				*out.DisabledDate = string(in.String())
			}
		case "disable_reason":
			if in.IsNull() {
				in.Skip()
				out.DisabledReason = nil
			} else {
				if out.DisabledReason == nil {
					out.DisabledReason = new(string)
				}
				*out.DisabledReason = string(in.String())
			}
		case "post_install_defined":
			out.PostInstallDefined = bool(in.Bool())
		case "service":
			if in.IsNull() {
				in.Skip()
				out.Service = nil
			} else {
				if out.Service == nil {
					out.Service = new(common.Service)
				}
				easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon1(in, out.Service)
			}
		case "tap_git_head":
			out.TapGitHead = string(in.String())
		case "ruby_source_path":
			out.RubySourcePath = string(in.String())
		case "ruby_source_checksum":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.RubySourceChecksum = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v92 string
					v92 = string(in.String())
					(out.RubySourceChecksum)[key] = v92
					in.WantComma()
				}
				in.Delim('}')
			}
		case "head_dependencies":
			if in.IsNull() {
				in.Skip()
				out.HeadDependencies = nil
			} else {
				if out.HeadDependencies == nil {
					out.HeadDependencies = new(HeadDependencies)
				}
				(*out.HeadDependencies).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV16(out *jwriter.Writer, in Info) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"variations\":"
		out.RawString(prefix[1:])
		if in.Variations == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v93First := true
			for v93Name, v93Value := range in.Variations {
				if v93First {
					v93First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v93Name))
				out.RawByte(':')
				if v93Value == nil {
					out.RawString("null")
				} else {
					(*v93Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"full_name\":"
		out.RawString(prefix)
		out.String(string(in.FullName))
	}
	{
		const prefix string = ",\"tap\":"
		out.RawString(prefix)
		out.String(string(in.Tap))
	}
	{
		const prefix string = ",\"oldname\":"
		out.RawString(prefix)
		out.String(string(in.OldName))
	}
	{
		const prefix string = ",\"oldnames\":"
		out.RawString(prefix)
		if in.OldNames == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v94, v95 := range in.OldNames {
				if v94 > 0 {
					out.RawByte(',')
				}
				out.String(string(v95))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"aliases\":"
		out.RawString(prefix)
		if in.Aliases == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v96, v97 := range in.Aliases {
				if v96 > 0 {
					out.RawByte(',')
				}
				out.String(string(v97))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"versioned_formulae\":"
		out.RawString(prefix)
		if in.VersionedFormulae == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v98, v99 := range in.VersionedFormulae {
				if v98 > 0 {
					out.RawByte(',')
				}
				out.String(string(v99))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"desc\":"
		out.RawString(prefix)
		out.String(string(in.Desc))
	}
	{
		const prefix string = ",\"license\":"
		out.RawString(prefix)
		out.String(string(in.License))
	}
	{
		const prefix string = ",\"homepage\":"
		out.RawString(prefix)
		out.String(string(in.Homepage))
	}
	{
		const prefix string = ",\"versions\":"
		out.RawString(prefix)
		(in.Versions).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"urls\":"
		out.RawString(prefix)
		if in.URLs == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v100First := true
			for v100Name, v100Value := range in.URLs {
				if v100First {
					v100First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v100Name))
				out.RawByte(':')
				(v100Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"revision\":"
		out.RawString(prefix)
		out.Int(int(in.Revision))
	}
	{
		const prefix string = ",\"version_scheme\":"
		out.RawString(prefix)
		out.Int(int(in.VersionScheme))
	}
	{
		const prefix string = ",\"bottle\":"
		out.RawString(prefix)
		if in.Bottle == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v101First := true
			for v101Name, v101Value := range in.Bottle {
				if v101First {
					v101First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v101Name))
				out.RawByte(':')
				if v101Value == nil {
					out.RawString("null")
				} else {
					(*v101Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"pour_bottle_only_if\":"
		out.RawString(prefix)
		if in.PourBottleOnlyIf == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PourBottleOnlyIf))
		}
	}
	{
		const prefix string = ",\"keg_only\":"
		out.RawString(prefix)
		out.Bool(bool(in.KegOnly))
	}
	{
		const prefix string = ",\"keg_only_reason\":"
		out.RawString(prefix)
		easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon(out, in.KegOnlyReason)
	}
	{
		const prefix string = ",\"options\":"
		out.RawString(prefix)
		if in.Options == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v102, v103 := range in.Options {
				if v102 > 0 {
					out.RawByte(',')
				}
				if m, ok := v103.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v103.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v103))
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"build_dependencies\":"
		out.RawString(prefix)
		if in.BuildDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v104, v105 := range in.BuildDependencies {
				if v104 > 0 {
					out.RawByte(',')
				}
				out.String(string(v105))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"dependencies\":"
		out.RawString(prefix)
		if in.Dependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v106, v107 := range in.Dependencies {
				if v106 > 0 {
					out.RawByte(',')
				}
				out.String(string(v107))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"test_dependencies\":"
		out.RawString(prefix)
		if in.TestDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v108, v109 := range in.TestDependencies {
				if v108 > 0 {
					out.RawByte(',')
				}
				out.String(string(v109))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"recommended_dependencies\":"
		out.RawString(prefix)
		if in.RecommendedDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v110, v111 := range in.RecommendedDependencies {
				if v110 > 0 {
					out.RawByte(',')
				}
				out.String(string(v111))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"optional_dependencies\":"
		out.RawString(prefix)
		if in.OptionalDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v112, v113 := range in.OptionalDependencies {
				if v112 > 0 {
					out.RawByte(',')
				}
				out.String(string(v113))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"uses_from_macos\":"
		out.RawString(prefix)
		if in.UsesFromMacOS == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v114, v115 := range in.UsesFromMacOS {
				if v114 > 0 {
					out.RawByte(',')
				}
				if m, ok := v115.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v115.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v115))
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"uses_from_macos_bounds\":"
		out.RawString(prefix)
		if in.UsesFromMacOSBounds == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v116, v117 := range in.UsesFromMacOSBounds {
				if v116 > 0 {
					out.RawByte(',')
				}
				if v117 == nil {
					out.RawString("null")
				} else {
					(*v117).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"requirements\":"
		out.RawString(prefix)
		if in.Requirements == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v118, v119 := range in.Requirements {
				if v118 > 0 {
					out.RawByte(',')
				}
				if v119 == nil {
					out.RawString("null")
				} else {
					(*v119).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"conflicts_with\":"
		out.RawString(prefix)
		if in.ConflictsWith == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v120, v121 := range in.ConflictsWith {
				if v120 > 0 {
					out.RawByte(',')
				}
				out.String(string(v121))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"conflicts_with_reasons\":"
		out.RawString(prefix)
		if in.ConflictsWithReasons == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v122, v123 := range in.ConflictsWithReasons {
				if v122 > 0 {
					out.RawByte(',')
				}
				out.String(string(v123))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"link_overwrite\":"
		out.RawString(prefix)
		if in.LinkOverwrite == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v124, v125 := range in.LinkOverwrite {
				if v124 > 0 {
					out.RawByte(',')
				}
				out.String(string(v125))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"caveats\":"
		out.RawString(prefix)
		if in.Caveats == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Caveats))
		}
	}
	{
		const prefix string = ",\"installed\":"
		out.RawString(prefix)
		if in.Installed == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v126, v127 := range in.Installed {
				if v126 > 0 {
					out.RawByte(',')
				}
				(v127).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"linked_keg\":"
		out.RawString(prefix)
		out.String(string(in.LinkedKeg))
	}
	{
		const prefix string = ",\"pinned\":"
		out.RawString(prefix)
		out.Bool(bool(in.Pinned))
	}
	{
		const prefix string = ",\"outdated\":"
		out.RawString(prefix)
		out.Bool(bool(in.Outdated))
	}
	{
		const prefix string = ",\"deprecated\":"
		out.RawString(prefix)
		out.Bool(bool(in.Deprecated))
	}
	{
		const prefix string = ",\"deprecation_date\":"
		out.RawString(prefix)
		if in.DeprecationDate == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DeprecationDate))
		}
	}
	{
		const prefix string = ",\"deprecation_reason\":"
		out.RawString(prefix)
		if in.DeprecationReason == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DeprecationReason))
		}
	}
	{
		const prefix string = ",\"disabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Disabled))
	}
	{
		const prefix string = ",\"disable_date\":"
		out.RawString(prefix)
		if in.DisabledDate == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DisabledDate))
		}
	}
	{
		const prefix string = ",\"disable_reason\":"
		out.RawString(prefix)
		if in.DisabledReason == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DisabledReason))
		}
	}
	{
		const prefix string = ",\"post_install_defined\":"
		out.RawString(prefix)
		out.Bool(bool(in.PostInstallDefined))
	}
	{
		const prefix string = ",\"service\":"
		out.RawString(prefix)
		if in.Service == nil {
			out.RawString("null")
		} else {
			easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShCommon1(out, *in.Service)
		}
	}
	{
		const prefix string = ",\"tap_git_head\":"
		out.RawString(prefix)
		out.String(string(in.TapGitHead))
	}
	{
		const prefix string = ",\"ruby_source_path\":"
		out.RawString(prefix)
		out.String(string(in.RubySourcePath))
	}
	{
		const prefix string = ",\"ruby_source_checksum\":"
		out.RawString(prefix)
		if in.RubySourceChecksum == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v128First := true
			for v128Name, v128Value := range in.RubySourceChecksum {
				if v128First {
					v128First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v128Name))
				out.RawByte(':')
				out.String(string(v128Value))
			}
			out.RawByte('}')
		}
	}
	if in.HeadDependencies != nil {
		const prefix string = ",\"head_dependencies\":"
		out.RawString(prefix)
		(*in.HeadDependencies).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Info) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Info) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Info) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Info) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV16(l, v)
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV17(in *jlexer.Lexer, out *HeadDependencies) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "build_dependencies":
			if in.IsNull() {
				in.Skip()
				out.BuildDependencies = nil
			} else {
				in.Delim('[')
				if out.BuildDependencies == nil {
					if !in.IsDelim(']') {
						out.BuildDependencies = make([]string, 0, 4)
					} else {
						out.BuildDependencies = []string{}
					}
				} else {
					out.BuildDependencies = (out.BuildDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v129 string
					v129 = string(in.String())
					out.BuildDependencies = append(out.BuildDependencies, v129)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "dependencies":
			if in.IsNull() {
				in.Skip()
				out.Dependencies = nil
			} else {
				in.Delim('[')
				if out.Dependencies == nil {
					if !in.IsDelim(']') {
						out.Dependencies = make([]string, 0, 4)
					} else {
						out.Dependencies = []string{}
					}
				} else {
					out.Dependencies = (out.Dependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v130 string
					v130 = string(in.String())
					out.Dependencies = append(out.Dependencies, v130)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "test_dependencies":
			if in.IsNull() {
				in.Skip()
				out.TestDependencies = nil
			} else {
				in.Delim('[')
				if out.TestDependencies == nil {
					if !in.IsDelim(']') {
						out.TestDependencies = make([]string, 0, 4)
					} else {
						out.TestDependencies = []string{}
					}
				} else {
					out.TestDependencies = (out.TestDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v131 string
					v131 = string(in.String())
					out.TestDependencies = append(out.TestDependencies, v131)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "recommended_dependencies":
			if in.IsNull() {
				in.Skip()
				out.RecommendedDependencies = nil
			} else {
				in.Delim('[')
				if out.RecommendedDependencies == nil {
					if !in.IsDelim(']') {
						out.RecommendedDependencies = make([]string, 0, 4)
					} else {
						out.RecommendedDependencies = []string{}
					}
				} else {
					out.RecommendedDependencies = (out.RecommendedDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v132 string
					v132 = string(in.String())
					out.RecommendedDependencies = append(out.RecommendedDependencies, v132)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "optional_dependencies":
			if in.IsNull() {
				in.Skip()
				out.OptionalDependencies = nil
			} else {
				in.Delim('[')
				if out.OptionalDependencies == nil {
					if !in.IsDelim(']') {
						out.OptionalDependencies = make([]string, 0, 4)
					} else {
						out.OptionalDependencies = []string{}
					}
				} else {
					out.OptionalDependencies = (out.OptionalDependencies)[:0]
				}
				for !in.IsDelim(']') {
					var v133 string
					v133 = string(in.String())
					out.OptionalDependencies = append(out.OptionalDependencies, v133)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "uses_from_macos":
			if in.IsNull() {
				in.Skip()
				out.UsesFromMacOS = nil
			} else {
				in.Delim('[')
				if out.UsesFromMacOS == nil {
					if !in.IsDelim(']') {
						out.UsesFromMacOS = make([]interface{}, 0, 4)
					} else {
						out.UsesFromMacOS = []interface{}{}
					}
				} else {
					out.UsesFromMacOS = (out.UsesFromMacOS)[:0]
				}
				for !in.IsDelim(']') {
					var v134 interface{}
					if m, ok := v134.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v134.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v134 = in.Interface()
					}
					out.UsesFromMacOS = append(out.UsesFromMacOS, v134)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "uses_from_macos_bounds":
			if in.IsNull() {
				in.Skip()
				out.UsesFromMacOSBounds = nil
			} else {
				in.Delim('[')
				if out.UsesFromMacOSBounds == nil {
					if !in.IsDelim(']') {
						out.UsesFromMacOSBounds = make([]*MacOSBounds, 0, 8)
					} else {
						out.UsesFromMacOSBounds = []*MacOSBounds{}
					}
				} else {
					out.UsesFromMacOSBounds = (out.UsesFromMacOSBounds)[:0]
				}
				for !in.IsDelim(']') {
					var v135 *MacOSBounds
					if in.IsNull() {
						in.Skip()
						v135 = nil
					} else {
						if v135 == nil {
							v135 = new(MacOSBounds)
						}
						(*v135).UnmarshalEasyJSON(in)
					}
					out.UsesFromMacOSBounds = append(out.UsesFromMacOSBounds, v135)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV17(out *jwriter.Writer, in HeadDependencies) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"build_dependencies\":"
		out.RawString(prefix[1:])
		if in.BuildDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v136, v137 := range in.BuildDependencies {
				if v136 > 0 {
					out.RawByte(',')
				}
				out.String(string(v137))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"dependencies\":"
		out.RawString(prefix)
		if in.Dependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v138, v139 := range in.Dependencies {
				if v138 > 0 {
					out.RawByte(',')
				}
				out.String(string(v139))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"test_dependencies\":"
		out.RawString(prefix)
		if in.TestDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v140, v141 := range in.TestDependencies {
				if v140 > 0 {
					out.RawByte(',')
				}
				out.String(string(v141))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"recommended_dependencies\":"
		out.RawString(prefix)
		if in.RecommendedDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v142, v143 := range in.RecommendedDependencies {
				if v142 > 0 {
					out.RawByte(',')
				}
				out.String(string(v143))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"optional_dependencies\":"
		out.RawString(prefix)
		if in.OptionalDependencies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v144, v145 := range in.OptionalDependencies {
				if v144 > 0 {
					out.RawByte(',')
				}
				out.String(string(v145))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"uses_from_macos\":"
		out.RawString(prefix)
		if in.UsesFromMacOS == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v146, v147 := range in.UsesFromMacOS {
				if v146 > 0 {
					out.RawByte(',')
				}
				if m, ok := v147.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v147.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v147))
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"uses_from_macos_bounds\":"
		out.RawString(prefix)
		if in.UsesFromMacOSBounds == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v148, v149 := range in.UsesFromMacOSBounds {
				if v148 > 0 {
					out.RawByte(',')
				}
				if v149 == nil {
					out.RawString("null")
				} else {
					(*v149).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HeadDependencies) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HeadDependencies) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HeadDependencies) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HeadDependencies) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV17(l, v)
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV18(in *jlexer.Lexer, out *FormulaURL) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "url":
			out.URL = string(in.String())
		case "branch":
			out.Branch = string(in.String())
		case "tag":
			out.Tag = string(in.String())
		case "revision":
			out.Revision = string(in.String())
		case "using":
			out.Using = string(in.String())
		case "checksum":
			out.Checksum = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV18(out *jwriter.Writer, in FormulaURL) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	if in.Branch != "" {
		const prefix string = ",\"branch\":"
		out.RawString(prefix)
		out.String(string(in.Branch))
	}
	if in.Tag != "" {
		const prefix string = ",\"tag\":"
		out.RawString(prefix)
		out.String(string(in.Tag))
	}
	if in.Revision != "" {
		const prefix string = ",\"revision\":"
		out.RawString(prefix)
		out.String(string(in.Revision))
	}
	if in.Using != "" {
		const prefix string = ",\"using\":"
		out.RawString(prefix)
		out.String(string(in.Using))
	}
	if in.Checksum != "" {
		const prefix string = ",\"checksum\":"
		out.RawString(prefix)
		out.String(string(in.Checksum))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FormulaURL) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV18(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FormulaURL) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV18(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FormulaURL) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV18(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FormulaURL) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV18(l, v)
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV19(in *jlexer.Lexer, out *BottleFile) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cellar":
			out.Cellar = string(in.String())
		case "url":
			out.URL = string(in.String())
		case "sha256":
			out.Sha256 = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV19(out *jwriter.Writer, in BottleFile) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cellar\":"
		out.RawString(prefix[1:])
		out.String(string(in.Cellar))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"sha256\":"
		out.RawString(prefix)
		out.String(string(in.Sha256))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BottleFile) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV19(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BottleFile) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV19(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BottleFile) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV19(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BottleFile) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV19(l, v)
}
func easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV110(in *jlexer.Lexer, out *Bottle) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "rebuild":
			out.Rebuild = int(in.Int())
		case "root_url":
			out.RootURL = string(in.String())
		case "files":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Files = make(map[platform.Platform]*BottleFile)
				for !in.IsDelim('}') {
					key := platform.Platform(in.String())
					in.WantColon()
					var v150 *BottleFile
					if in.IsNull() {
						in.Skip()
						v150 = nil
					} else {
						if v150 == nil {
							v150 = new(BottleFile)
						}
						(*v150).UnmarshalEasyJSON(in)
					}
					(out.Files)[key] = v150
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV110(out *jwriter.Writer, in Bottle) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rebuild\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Rebuild))
	}
	{
		const prefix string = ",\"root_url\":"
		out.RawString(prefix)
		out.String(string(in.RootURL))
	}
	{
		const prefix string = ",\"files\":"
		out.RawString(prefix)
		if in.Files == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v151First := true
			for v151Name, v151Value := range in.Files {
				if v151First {
					v151First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v151Name))
				out.RawByte(':')
				if v151Value == nil {
					out.RawString("null")
				} else {
					(*v151Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Bottle) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV110(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Bottle) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson102f8a2fEncodeGithubComAct3AiHopsInternalApisFormulaeBrewShV110(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Bottle) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV110(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Bottle) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson102f8a2fDecodeGithubComAct3AiHopsInternalApisFormulaeBrewShV110(l, v)
}
