name: Build ko image

on:
  release:
    types:
      - "created"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ko-build:
    name: Build ko image
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: ghcr.io/act3-ai/hops/distroless
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - uses: actions/checkout@v4
      - uses: ko-build/setup-ko@v0.6
      - run: ko build

  ko-publish-release-yaml:
    name: Publish Release YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: actions/checkout@v4
      - uses: ko-build/setup-ko@v0.6

      - name: Generate and upload release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(echo ${{ github.ref }} | cut -c11-)  # get tag name without tags/refs/ prefix.
          ko resolve -t ${tag} -f config/ > release.yaml
          gh release upload ${tag} release.yaml
