name: Build FIPS

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  go-build-fips:
    name: Go build FIPS
    runs-on: ubuntu-latest
    env:
      BUILD_ID: hops-fips
      EXECUTABLE: hops
      VERSION: ${{ github.ref_type == 'tag' && github.ref_name || format('{0}-{1}', github.workflow, github.sha) }}-fips
      CGO_ENABLED: 1
      GOEXPERIMENT: boringcrypto
    strategy:
      matrix:
        GOOS:
          - linux
          # - windows
          # - darwin
        GOARCH:
          - amd64
          # - arm64
      fail-fast: true
    steps:
      - uses: ./.github/workflows/build.yml