name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # upload archives to GitHub release
  packages: write # push images and packages to ghcr.io
  # issues: write # close milestones

env:
  GO_VERSION: "1.22"

jobs:
  goreleaser:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install tools
      - uses: taiki-e/install-action@v2
        with:
          tool: git-cliff
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Set up ko
        uses: ko-build/setup-ko@v0.8
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          install-only: true

      # Authenticate to registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Do the release stuff
      - name: Generate release notes
        run: |
          git-cliff --current --strip header >>"$GITHUB_STEP_SUMMARY"
          # RELEASE_NOTES=$(git-cliff --current --strip header)
          # echo "release-notes=\"$RELEASE_NOTES\"" >>"$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        run: |
          goreleaser release --clean --release-notes <(git-cliff --current --strip header | tail -n +3)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_DEPLOY_KEY: ${{ secrets.TAP_DEPLOY_KEY }}
